version: '3.8'

services:       # précise les différents services (images) à utiliser 

 nginx:
  container_name: nginx
  build: requirements/nginx/
  env_file: 
    - .env              # indique le fichier optionnel contenant l'environnement
  volumes:
   - wordpress:/var/www/html
  ports:
   - "443:443"                  # le port, détaillé juste en dessous
  restart: always             # Permet de redémarrer automatiquement le container en cas de crash
  networks:
   - inception                 # indique le nom du réseau à utiliser
  depends_on:                 # indique les dépendances du service
   - wordpress

 mariadb:
  container_name: mariadb
  build: requirements/mariadb/
  volumes:
   - db:/var/lib/mysql
  networks:
   - inception
  restart: always
  environment:
   MYSQL_DATABASE: ${MYSQL_DATABASE}
   MYSQL_USER: ${MYSQL_USER}
   MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  healthcheck: 
   test: ["CMD", "cat" ,"/tmp/ok"] # indique la commande à utiliser pour vérifier la santé du service
   interval: 10s # indique l'intervalle de temps entre chaque test

 wordpress:
  container_name: wordpress
  build: requirements/wordpress/
  volumes:
   - wordpress:/var/www/html
  networks:
   - inception
  restart: always
  environment:
   DOMAIN_NAME: ${DOMAIN_NAME}
   WP_ADMIN_NAME: ${WP_ADMIN_NAME}
   WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
   WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
   WP_GUEST_NAME: ${WP_GUEST_NAME}
   WP_GUEST_PASSWORD: ${WP_GUEST_PASSWORD}
   WP_GUEST_EMAIL: ${WP_GUEST_EMAIL}
   MYSQL_USER: ${MYSQL_USER}
   MYSQL_PASSWORD: ${MYSQL_PASSWORD}
   MYSQL_DATABASE: ${MYSQL_DATABASE}
  depends_on:
   mariadb :
    condition: service_healthy

volumes:
  wordpress:
   driver: local
   driver_opts:
    type: none
    device: /home/bchabot/data/wordpress
    o: bind
 
  db:
   driver: local
   driver_opts:
    type: none
    device: /home/bchabot/data/db
    o: bind

networks:
 inception:
  driver: bridge